version: '3.8'

services:
  rabbitmq:
    restart: always
    image: jkoniusz/rsww-179919-rabbitmq:v1
    ports:
      - 17996:15672 # adminer rabbit
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq_admin
      RABBITMQ_DEFAULT_PASS: rabbitmq
    hostname: rabbitmq
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 5s
      retries: 5
      timeout: 10s

#
# -------------------------------API GATEWAY-------------------------------
#

  api_gateway:
    restart: always
    image: jkoniusz/rsww-179919-api-gateway:v1
    ports:
      - 17991:8040
    command: bash -c "flask db upgrade && flask run --host 0.0.0.0 --port 8040"
    environment:
      FLASK_DEBUG: 'true'
      FLASK_ENV: production
      FLASK_APP: app_wsgi.py
      NO_WSGI: 'true'
      PG_USER: 179919_api_gateway
      PG_PASSWORD: api_gateway
      PG_DB: rsww_179919_api_gateway
      PG_HOST: 'actina20.maas'
      PG_PORT: 5432
      RESERVATION_SERVICE_ROOT_URL: http://reservation_api:8000/api
      PAYMENT_SERVICE_ROOT_URL: http://payment_api:8030/api
      TRIP_OFFER_SERVICE_ROOT_URL: http://trip_offer_api:8010/api

# 
# -------------------------------RESERVATION API-------------------------------
#
  reservation_api:
    restart: always
    image: jkoniusz/rsww-179919-reservation-service:v1
    command: bash -c "flask db upgrade && flask run --host 0.0.0.0 --port 8000"
    environment:
      FLASK_DEBUG: 'false'
      FLASK_ENV: production
      FLASK_APP: app_wsgi.py
      NO_WSGI: 'true'
      PG_USER: 179919_reservation
      PG_PASSWORD: reservation
      PG_DB: rsww_179919_reservation
      PG_HOST: 'actina20.maas'
      PG_PORT: 5432
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: reservation_user
      RABBITMQ_PASSWORD: password

# 
# -------------------------------PAYMENT API-------------------------------
# 
  payment_api:
    restart: always
    image: jkoniusz/rsww-179919-payment-service:v1
    command: bash -c "flask db upgrade && flask run --host 0.0.0.0 --port 8030"
    environment:
      FLASK_DEBUG: 'false'
      FLASK_ENV: production
      FLASK_APP: app_wsgi.py
      NO_WSGI: 'true'
      PG_USER: 179919_payment
      PG_PASSWORD: payment
      PG_DB: rsww_179919_payment
      PG_HOST: 'actina20.maas'
      PG_PORT: 5432
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: payment_user
      RABBITMQ_PASSWORD: password

# 
# -------------------------------TRIP OFFER API-------------------------------
# 
  trip_offer_api:
    restart: always
    image: jkoniusz/rsww-179919-trip-offer-service:v1
    command: flask run --host 0.0.0.0 --port 8010
    environment:
      FLASK_DEBUG: 'false'
      FLASK_ENV: production
      FLASK_APP: app_wsgi.py
      NO_WSGI: 'true'
      MONGO_USER: 179919_trip_offer
      MONGO_PASSWORD: trip_offer
      MONGO_DB: rsww_179919_trip_offer
      MONGO_HOST: 'actina15.maas'
      MONGO_PORT: 27017
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: rabbitmq_admin
      RABBITMQ_PASSWORD: rabbitmq

# 
# -------------------------------TOUR_OPERATOR APP-------------------------------
#
  tour_operator:
    restart: always
    image: jkoniusz/rsww-179919-tour-operator-service:v1
    command: bash -c "alembic upgrade head && python3 main.py"
    environment:
      FLASK_DEBUG: 'false'
      FLASK_ENV: production
      FLASK_APP: app_wsgi.py
      NO_WSGI: 'true'
      PG_USER: 179919_tour_operator
      PG_PASSWORD: tour_operator
      PG_DB: rsww_179919_tour_operator
      PG_HOST: 'actina20.maas'
      PG_PORT: 5432
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: tour_operator_user
      RABBITMQ_PASSWORD: password

