version: '3.8'

services:
  rabbitmq:
    restart: always
    image: jkoniusz/rsww-179919-rabbitmq:v1
    ports:
      - 17996:15672 # adminer rabbit
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq_admin
      RABBITMQ_DEFAULT_PASS: rabbitmq
    hostname: rabbitmq
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://rabbitmq:15672" ]
      interval: 5s
      retries: 5
      timeout: 10s

