version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq_admin
      RABBITMQ_DEFAULT_PASS: rabbitmq
    hostname: rabbitmq
    networks:
      - rsww_backend_network

  pg_db:
    image: postgres:13
    container_name: pg_db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    networks:
      - rsww_backend_network

  mongo_db:
    image: mongo:4.4.9
    container_name: mongo_db
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb_admin
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    ports:
      - "27017:27017"
    networks:
      - rsww_backend_network

  payment_api:
    container_name: payment_api
    restart: always
    build:
      context: ../payment_service
    command: flask run --host 0.0.0.0 --port 8030
    environment:
      FLASK_DEBUG: 'true'
      FLASK_APP: app_wsgi.py
      NO_WSGI: 'true'
      PG_USER: payment
      PG_PASSWORD: payment
      PG_DB: payment_pg
      PG_HOST: pg_db
      PG_PORT: 5432
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: payment_user
      RABBITMQ_PASSWORD: password
    ports:
      - "8030:8030"
    networks:
      - rsww_backend_network

  reservation_api:
    container_name: reservation_apiC
    restart: always
    build:
      context: ../reservation_service
    command: flask run --host 0.0.0.0 --port 8000
    environment:
      FLASK_DEBUG: 'true'
      FLASK_APP: app_wsgi.py
      NO_WSGI: 'true'
      PG_USER: reservation
      PG_PASSWORD: reservation
      PG_DB: reservation_pg
      PG_HOST: pg_db
      PG_PORT: 5432
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: reservation_user
      RABBITMQ_PASSWORD: password
    ports:
      - "8000:8000"
    networks:
      - rsww_backend_network

  tour_operator:
    restart: always
    build:
      context: ../tour_operator_service
    command: python3 main.py
    environment:
      FLASK_DEBUG: 'true'
      FLASK_APP: app_wsgi.py
      NO_WSGI: 'true'
      PG_USER: tour_operator
      PG_PASSWORD: tour_operator
      PG_DB: tour_operator_pg
      PG_HOST: pg_db
      PG_PORT: 5432
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: tour_operator_user
      RABBITMQ_PASSWORD: password
    ports:
      - "8020:8020"
    networks:
      - rsww_backend_network

  trip_offer_api:
    container_name: trip_offer_api
    restart: always
    build:
      context: ../trip_offer_service
    command: flask run --host 0.0.0.0 --port 8010
    environment:
      FLASK_DEBUG: 'true'
      FLASK_APP: app_wsgi.py
      NO_WSGI: 'true'
      MONGO_USER: trip_offer
      MONGO_PASSWORD: trip_offer
      MONGO_DB: trip_offer_mongo
      MONGO_HOST: mongo_db
      MONGO_PORT: 27017
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: rabbitmq_admin
      RABBITMQ_PASSWORD: rabbitmq
    ports:
      - "8010:8010"
    networks:
      - rsww_backend_network

networks:
  rsww_backend_network:
    name: rsww_backend_network
    driver: bridge
